-- 코드를 입력하세요
SELECT
    FOOD_FACTORY.FACTORY_ID
    , FOOD_FACTORY.FACTORY_NAME
    , FOOD_FACTORY.ADDRESS
FROM FOOD_FACTORY
WHERE FOOD_FACTORY.ADDRESS LIKE '%강원도%'
ORDER BY FOOD_FACTORY.FACTORY_ID ASC